include:
  - docker-compose.hawk.yaml

services:
  iris_mpc_client:
    image: hawk-server-local-build:latest
    entrypoint: tail -f /dev/null
    env_file:
      - .test.env
    environment:
      - SMPC__DATABASE__URL=postgres://postgres:postgres@dev_db:5432/SMPC_dev_2
      - SMPC__PARTY_ID=2
      - SMPC__HAWK_SERVER_HEALTHCHECK_PORT=3002
    command: tail -f /dev/null
    depends_on:
      hawk_participant_0:
        condition: service_healthy
      hawk_participant_1:
        condition: service_healthy
      hawk_participant_2:
        condition: service_healthy
