graph_size = 1000
irises_path = "data/store.ndjson"
layer0_path = "results.txt"
prf_seed = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
echoice = "NaiveMinFHD"

[searcher]
M = [256, 256, 256, 20, 10]
M_max = [256, 10, 256, 20, 20]
ef_constr_search = [320, 320, 320, 320, 320]
ef_constr_insert = [320, 320, 320, 320, 320]
ef_search =  [320, 320, 320, 320, 320]
layer_probability = 0.25
top_layer_mode = "Default"
