[shares_generator.FromFile]
rng_seed = 42
selection_strategy = "All"

[request_batch.Complex]
batches = [
  [
    { label = "00-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "01-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "02-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "03-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "04-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "05-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "06-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "07-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "08-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 9 }, { index = 10 }] } } },
    { label = "09-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 9 }, { index = 10 }] } } },
    { label = "10-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 11 }, { index = 12 }] } } },
    { label = "11-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 11 }, { index = 12 }] } } },
    { label = "12-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 13 }, { index = 14 }] } } },
    { label = "13-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 13 }, { index = 14 }] } } },
    { label = "14-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 15 }, { index = 16 }] } } },
    { label = "15-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 15 }, { index = 16 }] } } },
    { label = "16-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 17 }, { index = 18 }] } } },
    { label = "17-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 17 }, { index = 18 }] } } },
    { label = "18-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 19 }, { index = 20 }] } } },
    { label = "19-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 19 }, { index = 20 }] } } },
    { label = "20-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 21 }, { index = 22 }] } } },
    { label = "21-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 21 }, { index = 22 }] } } },
    { label = "22-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 23 }, { index = 24 }] } } },
    { label = "23-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 23 }, { index = 24 }] } } },
    { label = "24-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 25 }, { index = 26 }] } } },
    { label = "25-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 25 }, { index = 26 }] } } },
    { label = "26-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 27 }, { index = 28 }] } } },
    { label = "27-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 27 }, { index = 28 }] } } },
    { label = "28-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 29 }, { index = 30 }] } } },
    { label = "29-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 29 }, { index = 30 }] } } },
    { label = "30-U-Normal", payload = { Uniqueness = { iris_pair = [{ index = 31 }, { index = 32 }] } } },
    { label = "31-U-Mirror", payload = { Mirrored = { iris_pair = [{ index = 31 }, { index = 32 }] } } },
  ],
]
