[shares_generator.FromFile]
rng_seed = 42
selection_strategy = "All"

[request_batch.Complex]
batches = [
  [
    { label = "00-U", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "01-U", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "02-U", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "03-U", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "04-U", payload = { Uniqueness = { iris_pair = [{ index = 9 }, { index = 10 }] } } },
    { label = "05-U", payload = { Uniqueness = { iris_pair = [{ index = 11 }, { index = 12 }] } } },
    { label = "06-U", payload = { Uniqueness = { iris_pair = [{ index = 13 }, { index = 14 }] } } },
    { label = "07-U", payload = { Uniqueness = { iris_pair = [{ index = 15 }, { index = 16 }] } } },
    { label = "08-U", payload = { Uniqueness = { iris_pair = [{ index = 17 }, { index = 18 }] } } },
    { label = "09-U", payload = { Uniqueness = { iris_pair = [{ index = 19 }, { index = 20 }] } } },
    { label = "10-U", payload = { Uniqueness = { iris_pair = [{ index = 21 }, { index = 22 }] } } },
    { label = "11-U", payload = { Uniqueness = { iris_pair = [{ index = 23 }, { index = 24 }] } } },
    { label = "12-U", payload = { Uniqueness = { iris_pair = [{ index = 25 }, { index = 26 }] } } },
    { label = "13-U", payload = { Uniqueness = { iris_pair = [{ index = 27 }, { index = 28 }] } } },
    { label = "14-U", payload = { Uniqueness = { iris_pair = [{ index = 29 }, { index = 30 }] } } },
    { label = "15-U", payload = { Uniqueness = { iris_pair = [{ index = 31 }, { index = 32 }] } } },
    { label = "16-U", payload = { Uniqueness = { iris_pair = [{ index = 33 }, { index = 34 }] } } },
    { label = "17-U", payload = { Uniqueness = { iris_pair = [{ index = 35 }, { index = 36 }] } } },
    { label = "18-U", payload = { Uniqueness = { iris_pair = [{ index = 37 }, { index = 38 }] } } },
    { label = "19-U", payload = { Uniqueness = { iris_pair = [{ index = 39 }, { index = 40 }] } } },
    { label = "20-U", payload = { Uniqueness = { iris_pair = [{ index = 41 }, { index = 42 }] } } },
    { label = "21-U", payload = { Uniqueness = { iris_pair = [{ index = 43 }, { index = 44 }] } } },
    { label = "22-U", payload = { Uniqueness = { iris_pair = [{ index = 45 }, { index = 46 }] } } },
    { label = "23-U", payload = { Uniqueness = { iris_pair = [{ index = 47 }, { index = 48 }] } } },
    { label = "24-U", payload = { Uniqueness = { iris_pair = [{ index = 49 }, { index = 50 }] } } },
    { label = "25-U", payload = { Uniqueness = { iris_pair = [{ index = 51 }, { index = 52 }] } } },
    { label = "26-U", payload = { Uniqueness = { iris_pair = [{ index = 53 }, { index = 54 }] } } },
    { label = "27-U", payload = { Uniqueness = { iris_pair = [{ index = 55 }, { index = 56 }] } } },
    { label = "28-U", payload = { Uniqueness = { iris_pair = [{ index = 57 }, { index = 58 }] } } },
    { label = "29-U", payload = { Uniqueness = { iris_pair = [{ index = 59 }, { index = 60 }] } } },
    { label = "30-U", payload = { Uniqueness = { iris_pair = [{ index = 61 }, { index = 62 }] } } },
    { label = "31-U", payload = { Uniqueness = { iris_pair = [{ index = 63 }, { index = 64 }] } } },
  ],
  [
    { label = "00-D", payload = { IdentityDeletion = { parent = "00-U" } } },
    { label = "01-D", payload = { IdentityDeletion = { parent = "01-U" } } },
    { label = "02-D", payload = { IdentityDeletion = { parent = "02-U" } } },
    { label = "03-D", payload = { IdentityDeletion = { parent = "03-U" } } },
    { label = "04-D", payload = { IdentityDeletion = { parent = "04-U" } } },
    { label = "05-D", payload = { IdentityDeletion = { parent = "05-U" } } },
    { label = "06-D", payload = { IdentityDeletion = { parent = "06-U" } } },
    { label = "07-D", payload = { IdentityDeletion = { parent = "07-U" } } },
    { label = "08-RA", payload = { Reauthorisation = { iris_pair = [{ index = 65 }, { index = 66 }], parent = "08-U" } } },
    { label = "09-RA", payload = { Reauthorisation = { iris_pair = [{ index = 67 }, { index = 68 }], parent = "09-U" } } },
    { label = "10-RA", payload = { Reauthorisation = { iris_pair = [{ index = 69 }, { index = 70 }], parent = "10-U" } } },
    { label = "11-RA", payload = { Reauthorisation = { iris_pair = [{ index = 71 }, { index = 72 }], parent = "11-U" } } },
    { label = "12-RA", payload = { Reauthorisation = { iris_pair = [{ index = 73 }, { index = 74 }], parent = "12-U" } } },
    { label = "13-RA", payload = { Reauthorisation = { iris_pair = [{ index = 75 }, { index = 76 }], parent = "13-U" } } },
    { label = "14-RA", payload = { Reauthorisation = { iris_pair = [{ index = 77 }, { index = 78 }], parent = "14-U" } } },
    { label = "15-RA", payload = { Reauthorisation = { iris_pair = [{ index = 79 }, { index = 80 }], parent = "15-U" } } },
    { label = "16-RC", payload = { ResetCheck = { iris_pair = [{ index = 81 }, { index = 82 }] } } },
    { label = "17-RC", payload = { ResetCheck = { iris_pair = [{ index = 83 }, { index = 84 }] } } },
    { label = "18-RC", payload = { ResetCheck = { iris_pair = [{ index = 85 }, { index = 86 }] } } },
    { label = "19-RC", payload = { ResetCheck = { iris_pair = [{ index = 87 }, { index = 88 }] } } },
    { label = "20-RC", payload = { ResetCheck = { iris_pair = [{ index = 89 }, { index = 90 }] } } },
    { label = "21-RC", payload = { ResetCheck = { iris_pair = [{ index = 91 }, { index = 92 }] } } },
    { label = "22-RC", payload = { ResetCheck = { iris_pair = [{ index = 93 }, { index = 94 }] } } },
    { label = "23-RC", payload = { ResetCheck = { iris_pair = [{ index = 95 }, { index = 96 }] } } },
    { label = "24-RU", payload = { ResetUpdate = { iris_pair = [{ index = 97 }, { index = 98 }], parent = "16-U" } } },
    { label = "25-RU", payload = { ResetUpdate = { iris_pair = [{ index = 99 }, { index = 100 }], parent = "17-U" } } },
    { label = "26-RU", payload = { ResetUpdate = { iris_pair = [{ index = 101 }, { index = 102 }], parent = "18-U" } } },
    { label = "27-RU", payload = { ResetUpdate = { iris_pair = [{ index = 103 }, { index = 104 }], parent = "19-U" } } },
    { label = "28-RU", payload = { ResetUpdate = { iris_pair = [{ index = 105 }, { index = 106 }], parent = "20-U" } } },
    { label = "29-RU", payload = { ResetUpdate = { iris_pair = [{ index = 107 }, { index = 108 }], parent = "21-U" } } },
    { label = "30-RU", payload = { ResetUpdate = { iris_pair = [{ index = 109 }, { index = 110 }], parent = "22-U" } } },
    { label = "31-RU", payload = { ResetUpdate = { iris_pair = [{ index = 111 }, { index = 112 }], parent = "23-U" } } },
  ],
  [
    { label = "00-U2", payload = { Uniqueness = { iris_pair = [{ index = 113 }, { index = 114 }] } } },
    { label = "01-U2", payload = { Uniqueness = { iris_pair = [{ index = 115 }, { index = 116 }] } } },
    { label = "02-U2", payload = { Uniqueness = { iris_pair = [{ index = 117 }, { index = 118 }] } } },
    { label = "03-U2", payload = { Uniqueness = { iris_pair = [{ index = 119 }, { index = 120 }] } } },
    { label = "04-U2", payload = { Uniqueness = { iris_pair = [{ index = 121 }, { index = 122 }] } } },
    { label = "05-U2", payload = { Uniqueness = { iris_pair = [{ index = 123 }, { index = 124 }] } } },
    { label = "06-U2", payload = { Uniqueness = { iris_pair = [{ index = 125 }, { index = 126 }] } } },
    { label = "07-U2", payload = { Uniqueness = { iris_pair = [{ index = 127 }, { index = 128 }] } } },
    { label = "08-U2", payload = { Uniqueness = { iris_pair = [{ index = 129 }, { index = 130 }] } } },
    { label = "09-U2", payload = { Uniqueness = { iris_pair = [{ index = 131 }, { index = 132 }] } } },
    { label = "10-U2", payload = { Uniqueness = { iris_pair = [{ index = 133 }, { index = 134 }] } } },
    { label = "11-U2", payload = { Uniqueness = { iris_pair = [{ index = 135 }, { index = 136 }] } } },
    { label = "12-U2", payload = { Uniqueness = { iris_pair = [{ index = 137 }, { index = 138 }] } } },
    { label = "13-U2", payload = { Uniqueness = { iris_pair = [{ index = 139 }, { index = 140 }] } } },
    { label = "14-U2", payload = { Uniqueness = { iris_pair = [{ index = 141 }, { index = 142 }] } } },
    { label = "15-U2", payload = { Uniqueness = { iris_pair = [{ index = 143 }, { index = 144 }] } } },
    { label = "16-D2", payload = { IdentityDeletion = { parent = "24-U" } } },
    { label = "17-D2", payload = { IdentityDeletion = { parent = "25-U" } } },
    { label = "18-D2", payload = { IdentityDeletion = { parent = "26-U" } } },
    { label = "19-D2", payload = { IdentityDeletion = { parent = "27-U" } } },
    { label = "20-RA2", payload = { Reauthorisation = { iris_pair = [{ index = 145 }, { index = 146 }], parent = "28-U" } } },
    { label = "21-RA2", payload = { Reauthorisation = { iris_pair = [{ index = 147 }, { index = 148 }], parent = "29-U" } } },
    { label = "22-RA2", payload = { Reauthorisation = { iris_pair = [{ index = 149 }, { index = 150 }], parent = "30-U" } } },
    { label = "23-RA2", payload = { Reauthorisation = { iris_pair = [{ index = 151 }, { index = 152 }], parent = "31-U" } } },
    { label = "24-RC2", payload = { ResetCheck = { iris_pair = [{ index = 153 }, { index = 154 }] } } },
    { label = "25-RC2", payload = { ResetCheck = { iris_pair = [{ index = 155 }, { index = 156 }] } } },
    { label = "26-RC2", payload = { ResetCheck = { iris_pair = [{ index = 157 }, { index = 158 }] } } },
    { label = "27-RC2", payload = { ResetCheck = { iris_pair = [{ index = 159 }, { index = 160 }] } } },
    { label = "28-RU2", payload = { ResetUpdate = { iris_pair = [{ index = 161 }, { index = 162 }], parent = "24-U" } } },
    { label = "29-RU2", payload = { ResetUpdate = { iris_pair = [{ index = 163 }, { index = 164 }], parent = "25-U" } } },
    { label = "30-RU2", payload = { ResetUpdate = { iris_pair = [{ index = 165 }, { index = 166 }], parent = "26-U" } } },
    { label = "31-RU2", payload = { ResetUpdate = { iris_pair = [{ index = 167 }, { index = 168 }], parent = "27-U" } } },
  ],
]
