[shares_generator.FromFile]
rng_seed = 42
selection_strategy = "All"

[request_batch.Complex]
batches = [
  [
    { label = "00-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "01-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "02-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "03-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "04-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "05-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "06-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "07-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "08-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "09-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "10-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "11-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "12-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "13-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "14-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "15-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "16-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "17-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "18-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "19-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "20-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "21-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "22-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "23-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "24-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "25-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "26-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "27-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "28-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "29-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "30-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "31-U-Dup", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
  ],
  [
    { label = "00-D-Dup", payload = { IdentityDeletion = { parent = "00-U-Dup" } } },
    { label = "01-D-Dup", payload = { IdentityDeletion = { parent = "01-U-Dup" } } },
    { label = "02-D-Dup", payload = { IdentityDeletion = { parent = "02-U-Dup" } } },
    { label = "03-D-Dup", payload = { IdentityDeletion = { parent = "03-U-Dup" } } },
    { label = "04-D-Dup", payload = { IdentityDeletion = { parent = "04-U-Dup" } } },
    { label = "05-D-Dup", payload = { IdentityDeletion = { parent = "05-U-Dup" } } },
    { label = "06-D-Dup", payload = { IdentityDeletion = { parent = "06-U-Dup" } } },
    { label = "07-D-Dup", payload = { IdentityDeletion = { parent = "07-U-Dup" } } },
    { label = "08-D-Dup", payload = { IdentityDeletion = { parent = "08-U-Dup" } } },
    { label = "09-D-Dup", payload = { IdentityDeletion = { parent = "09-U-Dup" } } },
    { label = "10-D-Dup", payload = { IdentityDeletion = { parent = "10-U-Dup" } } },
    { label = "11-D-Dup", payload = { IdentityDeletion = { parent = "11-U-Dup" } } },
    { label = "12-D-Dup", payload = { IdentityDeletion = { parent = "12-U-Dup" } } },
    { label = "13-D-Dup", payload = { IdentityDeletion = { parent = "13-U-Dup" } } },
    { label = "14-D-Dup", payload = { IdentityDeletion = { parent = "14-U-Dup" } } },
    { label = "15-D-Dup", payload = { IdentityDeletion = { parent = "15-U-Dup" } } },
    { label = "16-D-Dup", payload = { IdentityDeletion = { parent = "16-U-Dup" } } },
    { label = "17-D-Dup", payload = { IdentityDeletion = { parent = "17-U-Dup" } } },
    { label = "18-D-Dup", payload = { IdentityDeletion = { parent = "18-U-Dup" } } },
    { label = "19-D-Dup", payload = { IdentityDeletion = { parent = "19-U-Dup" } } },
    { label = "20-D-Dup", payload = { IdentityDeletion = { parent = "20-U-Dup" } } },
    { label = "21-D-Dup", payload = { IdentityDeletion = { parent = "21-U-Dup" } } },
    { label = "22-D-Dup", payload = { IdentityDeletion = { parent = "22-U-Dup" } } },
    { label = "23-D-Dup", payload = { IdentityDeletion = { parent = "23-U-Dup" } } },
    { label = "24-D-Dup", payload = { IdentityDeletion = { parent = "24-U-Dup" } } },
    { label = "25-D-Dup", payload = { IdentityDeletion = { parent = "25-U-Dup" } } },
    { label = "26-D-Dup", payload = { IdentityDeletion = { parent = "26-U-Dup" } } },
    { label = "27-D-Dup", payload = { IdentityDeletion = { parent = "27-U-Dup" } } },
    { label = "28-D-Dup", payload = { IdentityDeletion = { parent = "28-U-Dup" } } },
    { label = "29-D-Dup", payload = { IdentityDeletion = { parent = "29-U-Dup" } } },
    { label = "30-D-Dup", payload = { IdentityDeletion = { parent = "30-U-Dup" } } },
    { label = "31-D-Dup", payload = { IdentityDeletion = { parent = "31-U-Dup" } } },
  ],
]
