[shares_generator.FromFile]
rng_seed = 42
selection_strategy = "All"

[request_batch.Complex]
batches = [
  [
    { label = "00-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 1 }, { index = 2 }] } } },
    { label = "01-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 3 }, { index = 4 }] } } },
    { label = "02-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 5 }, { index = 6 }] } } },
    { label = "03-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 7 }, { index = 8 }] } } },
    { label = "04-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 9 }, { index = 10 }] } } },
    { label = "05-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 11 }, { index = 12 }] } } },
    { label = "06-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 13 }, { index = 14 }] } } },
    { label = "07-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 15 }, { index = 16 }] } } },
    { label = "08-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 17 }, { index = 18 }] } } },
    { label = "09-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 19 }, { index = 20 }] } } },
    { label = "10-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 21 }, { index = 22 }] } } },
    { label = "11-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 23 }, { index = 24 }] } } },
    { label = "12-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 25 }, { index = 26 }] } } },
    { label = "13-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 27 }, { index = 28 }] } } },
    { label = "14-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 29 }, { index = 30 }] } } },
    { label = "15-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 31 }, { index = 32 }] } } },
    { label = "16-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 33 }, { index = 34 }] } } },
    { label = "17-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 35 }, { index = 36 }] } } },
    { label = "18-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 37 }, { index = 38 }] } } },
    { label = "19-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 39 }, { index = 40 }] } } },
    { label = "20-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 41 }, { index = 42 }] } } },
    { label = "21-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 43 }, { index = 44 }] } } },
    { label = "22-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 45 }, { index = 46 }] } } },
    { label = "23-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 47 }, { index = 48 }] } } },
    { label = "24-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 49 }, { index = 50 }] } } },
    { label = "25-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 51 }, { index = 52 }] } } },
    { label = "26-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 53 }, { index = 54 }] } } },
    { label = "27-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 55 }, { index = 56 }] } } },
    { label = "28-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 57 }, { index = 58 }] } } },
    { label = "29-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 59 }, { index = 60 }] } } },
    { label = "30-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 61 }, { index = 62 }] } } },
    { label = "31-U-Gen0", payload = { Uniqueness = { iris_pair = [{ index = 63 }, { index = 64 }] } } },
  ],
  [
    { label = "00-D-Gen0", payload = { IdentityDeletion = { parent = "00-U-Gen0" } } },
    { label = "01-D-Gen0", payload = { IdentityDeletion = { parent = "01-U-Gen0" } } },
    { label = "02-D-Gen0", payload = { IdentityDeletion = { parent = "02-U-Gen0" } } },
    { label = "03-D-Gen0", payload = { IdentityDeletion = { parent = "03-U-Gen0" } } },
    { label = "04-D-Gen0", payload = { IdentityDeletion = { parent = "04-U-Gen0" } } },
    { label = "05-D-Gen0", payload = { IdentityDeletion = { parent = "05-U-Gen0" } } },
    { label = "06-D-Gen0", payload = { IdentityDeletion = { parent = "06-U-Gen0" } } },
    { label = "07-D-Gen0", payload = { IdentityDeletion = { parent = "07-U-Gen0" } } },
    { label = "08-D-Gen0", payload = { IdentityDeletion = { parent = "08-U-Gen0" } } },
    { label = "09-D-Gen0", payload = { IdentityDeletion = { parent = "09-U-Gen0" } } },
    { label = "10-D-Gen0", payload = { IdentityDeletion = { parent = "10-U-Gen0" } } },
    { label = "11-D-Gen0", payload = { IdentityDeletion = { parent = "11-U-Gen0" } } },
    { label = "12-D-Gen0", payload = { IdentityDeletion = { parent = "12-U-Gen0" } } },
    { label = "13-D-Gen0", payload = { IdentityDeletion = { parent = "13-U-Gen0" } } },
    { label = "14-D-Gen0", payload = { IdentityDeletion = { parent = "14-U-Gen0" } } },
    { label = "15-D-Gen0", payload = { IdentityDeletion = { parent = "15-U-Gen0" } } },
    { label = "16-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 65 }, { index = 66 }] } } },
    { label = "17-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 67 }, { index = 68 }] } } },
    { label = "18-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 69 }, { index = 70 }] } } },
    { label = "19-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 71 }, { index = 72 }] } } },
    { label = "20-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 73 }, { index = 74 }] } } },
    { label = "21-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 75 }, { index = 76 }] } } },
    { label = "22-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 77 }, { index = 78 }] } } },
    { label = "23-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 79 }, { index = 80 }] } } },
    { label = "24-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 81 }, { index = 82 }] } } },
    { label = "25-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 83 }, { index = 84 }] } } },
    { label = "26-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 85 }, { index = 86 }] } } },
    { label = "27-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 87 }, { index = 88 }] } } },
    { label = "28-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 89 }, { index = 90 }] } } },
    { label = "29-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 91 }, { index = 92 }] } } },
    { label = "30-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 93 }, { index = 94 }] } } },
    { label = "31-U-Gen1", payload = { Uniqueness = { iris_pair = [{ index = 95 }, { index = 96 }] } } },
  ],
  [
    { label = "00-RA-Gen1", payload = { Reauthorisation = { iris_pair = [{ index = 97 }, { index = 98 }], parent = "16-U-Gen1" } } },
    { label = "01-RA-Gen1", payload = { Reauthorisation = { iris_pair = [{ index = 99 }, { index = 100 }], parent = "17-U-Gen1" } } },
    { label = "02-RA-Gen1", payload = { Reauthorisation = { iris_pair = [{ index = 101 }, { index = 102 }], parent = "18-U-Gen1" } } },
    { label = "03-RA-Gen1", payload = { Reauthorisation = { iris_pair = [{ index = 103 }, { index = 104 }], parent = "19-U-Gen1" } } },
    { label = "04-RA-Gen1", payload = { Reauthorisation = { iris_pair = [{ index = 105 }, { index = 106 }], parent = "20-U-Gen1" } } },
    { label = "05-RA-Gen1", payload = { Reauthorisation = { iris_pair = [{ index = 107 }, { index = 108 }], parent = "21-U-Gen1" } } },
    { label = "06-RA-Gen1", payload = { Reauthorisation = { iris_pair = [{ index = 109 }, { index = 110 }], parent = "22-U-Gen1" } } },
    { label = "07-RA-Gen1", payload = { Reauthorisation = { iris_pair = [{ index = 111 }, { index = 112 }], parent = "23-U-Gen1" } } },
    { label = "08-RU-Gen1", payload = { ResetUpdate = { iris_pair = [{ index = 113 }, { index = 114 }], parent = "24-U-Gen1" } } },
    { label = "09-RU-Gen1", payload = { ResetUpdate = { iris_pair = [{ index = 115 }, { index = 116 }], parent = "25-U-Gen1" } } },
    { label = "10-RU-Gen1", payload = { ResetUpdate = { iris_pair = [{ index = 117 }, { index = 118 }], parent = "26-U-Gen1" } } },
    { label = "11-RU-Gen1", payload = { ResetUpdate = { iris_pair = [{ index = 119 }, { index = 120 }], parent = "27-U-Gen1" } } },
    { label = "12-RU-Gen1", payload = { ResetUpdate = { iris_pair = [{ index = 121 }, { index = 122 }], parent = "28-U-Gen1" } } },
    { label = "13-RU-Gen1", payload = { ResetUpdate = { iris_pair = [{ index = 123 }, { index = 124 }], parent = "29-U-Gen1" } } },
    { label = "14-RU-Gen1", payload = { ResetUpdate = { iris_pair = [{ index = 125 }, { index = 126 }], parent = "30-U-Gen1" } } },
    { label = "15-RU-Gen1", payload = { ResetUpdate = { iris_pair = [{ index = 127 }, { index = 128 }], parent = "31-U-Gen1" } } },
    { label = "16-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 129 }, { index = 130 }] } } },
    { label = "17-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 131 }, { index = 132 }] } } },
    { label = "18-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 133 }, { index = 134 }] } } },
    { label = "19-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 135 }, { index = 136 }] } } },
    { label = "20-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 137 }, { index = 138 }] } } },
    { label = "21-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 139 }, { index = 140 }] } } },
    { label = "22-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 141 }, { index = 142 }] } } },
    { label = "23-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 143 }, { index = 144 }] } } },
    { label = "24-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 145 }, { index = 146 }] } } },
    { label = "25-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 147 }, { index = 148 }] } } },
    { label = "26-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 149 }, { index = 150 }] } } },
    { label = "27-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 151 }, { index = 152 }] } } },
    { label = "28-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 153 }, { index = 154 }] } } },
    { label = "29-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 155 }, { index = 156 }] } } },
    { label = "30-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 157 }, { index = 158 }] } } },
    { label = "31-U-Gen2", payload = { Uniqueness = { iris_pair = [{ index = 159 }, { index = 160 }] } } },
  ],
  [
    { label = "00-D-Gen0b", payload = { IdentityDeletion = { parent = "16-U-Gen0" } } },
    { label = "01-D-Gen0b", payload = { IdentityDeletion = { parent = "17-U-Gen0" } } },
    { label = "02-D-Gen0b", payload = { IdentityDeletion = { parent = "18-U-Gen0" } } },
    { label = "03-D-Gen0b", payload = { IdentityDeletion = { parent = "19-U-Gen0" } } },
    { label = "04-D-Gen0b", payload = { IdentityDeletion = { parent = "20-U-Gen0" } } },
    { label = "05-D-Gen0b", payload = { IdentityDeletion = { parent = "21-U-Gen0" } } },
    { label = "06-D-Gen0b", payload = { IdentityDeletion = { parent = "22-U-Gen0" } } },
    { label = "07-D-Gen0b", payload = { IdentityDeletion = { parent = "23-U-Gen0" } } },
    { label = "08-D-Gen0b", payload = { IdentityDeletion = { parent = "24-U-Gen0" } } },
    { label = "09-D-Gen0b", payload = { IdentityDeletion = { parent = "25-U-Gen0" } } },
    { label = "10-D-Gen0b", payload = { IdentityDeletion = { parent = "26-U-Gen0" } } },
    { label = "11-D-Gen0b", payload = { IdentityDeletion = { parent = "27-U-Gen0" } } },
    { label = "12-D-Gen0b", payload = { IdentityDeletion = { parent = "28-U-Gen0" } } },
    { label = "13-D-Gen0b", payload = { IdentityDeletion = { parent = "29-U-Gen0" } } },
    { label = "14-D-Gen0b", payload = { IdentityDeletion = { parent = "30-U-Gen0" } } },
    { label = "15-D-Gen0b", payload = { IdentityDeletion = { parent = "31-U-Gen0" } } },
    { label = "16-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 161 }, { index = 162 }], parent = "16-U-Gen2" } } },
    { label = "17-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 163 }, { index = 164 }], parent = "17-U-Gen2" } } },
    { label = "18-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 165 }, { index = 166 }], parent = "18-U-Gen2" } } },
    { label = "19-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 167 }, { index = 168 }], parent = "19-U-Gen2" } } },
    { label = "20-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 169 }, { index = 170 }], parent = "20-U-Gen2" } } },
    { label = "21-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 171 }, { index = 172 }], parent = "21-U-Gen2" } } },
    { label = "22-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 173 }, { index = 174 }], parent = "22-U-Gen2" } } },
    { label = "23-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 175 }, { index = 176 }], parent = "23-U-Gen2" } } },
    { label = "24-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 177 }, { index = 178 }], parent = "24-U-Gen2" } } },
    { label = "25-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 179 }, { index = 180 }], parent = "25-U-Gen2" } } },
    { label = "26-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 181 }, { index = 182 }], parent = "26-U-Gen2" } } },
    { label = "27-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 183 }, { index = 184 }], parent = "27-U-Gen2" } } },
    { label = "28-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 185 }, { index = 186 }], parent = "28-U-Gen2" } } },
    { label = "29-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 187 }, { index = 188 }], parent = "29-U-Gen2" } } },
    { label = "30-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 189 }, { index = 190 }], parent = "30-U-Gen2" } } },
    { label = "31-RU-Gen2", payload = { ResetUpdate = { iris_pair = [{ index = 191 }, { index = 192 }], parent = "31-U-Gen2" } } },
  ],
]
