[shares_generator.FromFile]
rng_seed = 42
selection_strategy = "All"

[request_batch.Complex]
batches = [
  [
    { label = "40-Uniqueness", payload = { Uniqueness = { iris_pair = [
      { index = 1 },
      { index = 2 },
    ] } } },
    { label = "41-Uniqueness", payload = { Uniqueness = { iris_pair = [
      { index = 3 },
      { index = 4 },
    ] } } },
    { label = "42-Uniqueness", payload = { Uniqueness = { iris_pair = [
      { index = 5 },
      { index = 6 },
    ] } } },
  ],
  [
    { label = "00-IdentityDeletion", payload = { IdentityDeletion = { parent = "40-Uniqueness" } } },
    { label = "10-Reauthorisation", payload = { Reauthorisation = { iris_pair = [
      { index = 11 },
      { index = 12 },
    ], parent = "41-Uniqueness" } } },
    { label = "20-ResetCheck", payload = { ResetCheck = { iris_pair = [
      { index = 13 },
      { index = 14 },
    ] } } },
    { label = "30-ResetUpdate", payload = { ResetUpdate = { iris_pair = [
      { index = 15 },
      { index = 16 },
    ], parent = "42-Uniqueness" } } },
  ],
  [
    { label = "01-DupDeletion", payload = { IdentityDeletion = { parent = "40-Uniqueness" } } },
    { label = "02-DupUniqueness", payload = { Uniqueness = { iris_pair = [
      { index = 1 },
      { index = 2 },
    ] } } },
    { label = "03-DupResetCheck", payload = { ResetCheck = { iris_pair = [
      { index = 13 },
      { index = 14 },
    ] } } },
  ],
]
