prestate = "44682ea86b704fb3c65cd16f84a76b621e04bbdb3746280f25cf062220e471b4"

[request_batch.Simple]
batch_count = 10
batch_size = 10
batch_kind = "reauth"
known_iris_serial_id = 1

[shares_generator.FromCompute]
rng_seed = 42
