distance_fn = "MinRotation"         # Must be "Simple" or "MinRotation"
hnsw_prf_seed = 42

[irises]
option = "NdjsonFile"
path = "data/store.ndjson"
limit = 1000
selection = "All"

# [graph]
# path = "data/starting-graph.dat"

[searcher]
layer_mode = { LinearScan = { max_graph_layer = 1 } }

[searcher.params]
option = "Standard"
ef_constr = 320
ef_search = 320
M = 256

[output]

# With checkpoints
base_directory = "data/"
filename_stem = "graph-320-256-minfhd"
checkpoints = { Regular = 250 }
# checkpoints = { Values = [400, 700, 900] }

# No checkpoints
# path = "data/graph-320-256-minfhd-1000.dat"
